services:
  bliss-wiki:
    container_name: bliss-wiki
    build: .
    volumes:
      - ./wiki:/app/wiki
    command: python -m wikmd.wiki

  cloudflared:
    container_name: wiki-cloudflared
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${WIKI_TUNNEL_TOKEN}
