# wikmd configuration file

wikmd_host: "0.0.0.0"
wikmd_port: 8000
wikmd_logging: 1
wikmd_logging_file: "wikmd.log"

git_user: "wikmd"
git_email: "wikmd@no-mail.com"

main_branch_name: "main"
sync_with_remote: 0
remote_url: ""

wiki_directory: "wiki"
homepage: "homepage.md"
homepage_title: "homepage"
images_route: "img"
image_allowed_mime: ["image/gif", "image/jpeg", "image/png", "image/svg+xml", "image/webp"]
hide_folder_in_wiki: [".obsidian"]

plugins: ["draw", "alerts", "mermaid", "embed-pages", "swagger"]

protect_edit_by_password: 1
password_in_sha_256: "31e0e19bc72dd1832ef5477ae8846f052cf88e247634b5a6980eb10766ccba44" #ps: wikmd 

local_mode: false

optimize_images: "no"

cache_dir: "./build/cache"
search_dir: "./build/searchindex"

secret_key: '\xfd{H\xe5<\x95\xf9\xe3\x96.5\xd1\x01O<!\xd5\xa2\xa0\x9fR"\xa1\xa8'